[tool.ruff]
ignore-init-module-imports = true
select = ["D", "E", "F"]
ignore = ["D205"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"docs/*" = ["D"]
"examples/*" = ["D"]
"test/*" = ["D"]
"./*.py" = ["D"]


[tool.ruff.pydocstyle]
# Use Google-style docstrings.
convention = "google"